### ISSUE TITLE
blast option qcov_hsp_perc not recognized

### ISSUE THREAD

**Issue by jocelyne8** [biopython/biopython#1375]
### Setup

I am reporting a problem with Biopython version, Python version, and operating
system as follows:
```
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sys; print(sys.version)
2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
>>> import platform; print(platform.python_implementation()); print(platform.platform())
CPython
Linux-3.10.0-514.26.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
>>> import Bio; print(Bio.__version__)
1.64
```

blast option qcov_hsp_perc not recognized. Added in BLAST+ 2.2.30:
https://www.ncbi.nlm.nih.gov/books/NBK131777/#_Blast_ReleaseNotes_BLAST_2_2_30_October_

```
blast_args['qcov_hsp_perc'] = perc_identity
blastn_cline = NcbiblastnCommandline(**blast_args)  # see **kwargs
```

### Expected behaviour

Start Blast

### Actual behaviour
```
  File "/pathto/anaconda/lib/python2.7/site-packages/Bio/Application/__init__.py", line 359, in set_parameter
    raise ValueError("Option name %s was not found." % name)
ValueError: Option name qcov_hsp_perc was not found.
```

### Steps to reproduce

```
blast_args['qcov_hsp_perc'] = perc_identity
blastn_cline = NcbiblastnCommandline(**blast_args)  # see **kwargs
```

**Comment by jocelyne8** [comment]
Actually, let me investigate. I see the code here:
https://github.com/biopython/biopython/blob/master/Bio/Blast/Applications.py#L173
And it's been there for 3 years according to blame...

**Comment by peterjc** [comment]
Biopython 1.64 was released May 2014 and the line you've spotted was added in Nov 2014 in 27b2c42a9e5106c79508d753568067c02faed78a - so Biopython 1.65  or later should be fine.

Can you update? The current release is Biopython 1.70.

**Comment by jocelyne8** [comment]
Yes, that's what I did. It just took forever for conda to install so I could test it. 
FYI 1.67 is the latest on conda.

**Comment by peterjc** [comment]
That's strange - which channels do you have setup on conda?

Conda-forge has Biopython 1.70 https://anaconda.org/conda-forge/biopython (as does BioConda but that won't be updated in future in favour of conda-forge).

Even the default channel has Biopython 1.69 https://anaconda.org/anaconda/biopython

**Comment by jocelyne8** [comment]
That's very odd. I'm using the default channels (see below), and both conda and biopython get an
"All requested packages already installed." on upgrade. Maybe I need to update anaconda itself.  That's a task for another day.

```
channel_alias: https://conda.anaconda.org

custom_channels:
  pkgs/r: https://repo.continuum.io/
  pkgs/pro: https://repo.continuum.io/
  pkgs/free: https://repo.continuum.io/
custom_multichannels:
  local: []
  defaults: ["https://repo.continuum.io/pkgs/free", "https://repo.continuum.io/pkgs/r", "https://repo.continuum.io/pkgs/pro"]
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
```
