### ISSUE TITLE
CodeCov too noisy on pull requests

### ISSUE THREAD

**Issue by peterjc** [biopython/biopython#2249]
We have automated functional tests running on TravisCI and AppVeyor, which report the test coverage to CodeCov https://codecov.io/github/biopython/biopython/

Additionally, CodeCov will report back on all pull requests about the change in coverage (for the whole codebase), and that of the lines changed.

We do not currently require these tests to pass, but if they fail the pull request still gets big red crosses against it, and looks like a problem on the PR listing:

https://github.com/biopython/biopython/pulls

I think this has reached the point where the pull request integration is arguably counter productive (especially for first time contributors getting this).

Ideally we would be able to configure the thresholds CodeCov uses for pull request status. Consider for example #2245 (a recent and very small change):

❌ codecov/project — 84.89% (-0.01%) compared to c582c56
✅ codecov/patch — Coverage not affected when comparing c582c56...033081b

In this case the tiny drop in overall coverage is just noise (there are still enough random values uses in our tests that we almost expect this), although it correctly found no change on the patch itself.

Or, look at #2134 with:

❌ codecov/project — 84.81% (-0.01%) compared to 4f2661b
❌ codecov/patch — 20% of diff hit (target 84.82%)

It seems CodeCov sets the target (here 84.82%) dynamically based on the overall project coverage - can we over-ride this? e.g. To a fixed value (say 75%), or relative?

This looks possible, see https://docs.codecov.io/docs/commit-status#section-advanced-configuration (although currently the site is having technical difficulties, the style and images are not showing)

**Comment by peterjc** [comment]
I've tried setting a Biopython team level default as follows in the CodeCov website:

```yaml
codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto 
    patch:
      default:
        # basic
        target: 75%
        threshold: 1%
        base: auto 
```

If this doesn't work, we can add a ``.codecov.yml`` in the project root of the git repo.

**Comment by peterjc** [comment]
Revised to:

```yaml
codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto 
    patch:
      default:
        # basic
        target: 50%
        threshold: 1%
        base: auto 
```

Perhaps the recent focus on code style and cleanup by its nature had lower coverage, but we've still have too many red crosses just because of CodeCov.
